/*
 * The Little Wow Balloons Instagram archive.
 *
 * @qianhaopower on Instagram was the studio's shopfront before the account
 * turned toward books and leadership. The photos are digital assets worth
 * keeping — they move here, into the library, where nothing expires.
 *
 * `items` is generated by `scripts/ingest-instagram-balloons.mjs` from the
 * official Instagram data export (Accounts Center → Download your
 * information). Never hand-write items; run the script. Removing a
 * non-balloon post afterwards = deleting its entry from
 * balloon-archive.json and its file from public/projects/balloons/.
 */

import archive from "./balloon-archive.json";

export type BalloonArchiveItem = {
  /** Path under /projects/balloons/, e.g. "/projects/balloons/ig-20250914-1.jpg" */
  src: string;
  /** Original Instagram caption (may be empty) */
  caption: string;
  /** ISO date, e.g. "2025-09-14" — absent when the photo carried no EXIF date */
  date?: string;
};

export const BALLOON_ARCHIVE_PROFILE = {
  handle: "qianhaopower",
  url: "https://www.instagram.com/qianhaopower/",
  logo: "/projects/balloons/studio-logo.jpg",
  bio: "✨ Turning air into WOW moments — custom balloon twisting & event fun for all ages. Markets · Parties · Celebrations.",
};

export const BALLOON_ARCHIVE_ITEMS: BalloonArchiveItem[] = archive.items;

/*
 * On the street — Hao's own photos from the stall: markets, festivals,
 * commissions. Curated by hand (not from the IG export); dates from EXIF.
 */
export const BALLOON_STREET_ITEMS: BalloonArchiveItem[] = [
  {
    src: "/projects/balloons/street-7.jpg",
    caption:
      "Three generations at the stall — grandparents, strollers and all. Box Hill Twilight Markets.",
    date: "2026-02-14",
  },
  {
    src: "/projects/balloons/street-1.jpg",
    caption:
      "The stand — small $10, large $20, buy three get one free. The QR code says scan to follow.",
  },
  {
    src: "/projects/balloons/street-2.jpg",
    caption:
      "Box Hill Twilight Markets, Valentine's Day — a drying rack makes a fine balloon tree.",
    date: "2026-02-14",
  },
  {
    src: "/projects/balloons/street-3.jpg",
    caption: "Evening orders at the Box Hill stall.",
  },
  {
    src: "/projects/balloons/street-4.jpg",
    caption:
      "Saturday night on the Southbank promenade — the city does the lighting.",
    date: "2026-03-07",
  },
  {
    src: "/projects/balloons/street-5.jpg",
    caption: "Mario, fresh off the pump — kitchen quality check.",
    date: "2026-03-12",
  },
  {
    src: "/projects/balloons/street-6.jpg",
    caption: "Mario and Luigi, the full crew.",
    date: "2026-03-13",
  },
];
