/*
 * The Little Wow Balloons Instagram archive.
 *
 * @qianhaopower on Instagram was the studio's shopfront before the account
 * turned toward books and leadership. The photos are digital assets worth
 * keeping — they move here, into the library, where nothing expires.
 *
 * `items` is generated by `scripts/ingest-instagram-balloons.mjs` from the
 * official Instagram data export (Accounts Center → Download your
 * information). Never hand-write items; run the script. Removing a
 * non-balloon post afterwards = deleting its entry from
 * balloon-archive.json and its file from public/projects/balloons/.
 */

import archive from "./balloon-archive.json";

export type BalloonArchiveItem = {
  /** Path under /projects/balloons/, e.g. "/projects/balloons/ig-20250914-1.jpg" */
  src: string;
  /** Original Instagram caption (may be empty) */
  caption: string;
  /** ISO date the post went up, e.g. "2025-09-14" */
  date: string;
};

export const BALLOON_ARCHIVE_PROFILE = {
  handle: "qianhaopower",
  url: "https://www.instagram.com/qianhaopower/",
  logo: "/projects/balloons/studio-logo.jpg",
  bio: "✨ Turning air into WOW moments — custom balloon twisting & event fun for all ages. Markets · Parties · Celebrations.",
};

export const BALLOON_ARCHIVE_ITEMS: BalloonArchiveItem[] = archive.items;
