import { Team } from "@wcf/types";

export const teams: Team[] = [
  // Host / World Cup teams
  {
    id: "canada",
    name: "Canada",
    code: "CAN",
    flag: "🇨🇦",
    category: "worldcup",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    accentColor: "#111827",
    specialMove: "Maple Counter",
    funnyTrait: "polite aggression",
  },
  {
    id: "mexico",
    name: "Mexico",
    code: "MEX",
    flag: "🇲🇽",
    category: "worldcup",
    primaryColor: "#006847",
    secondaryColor: "#FFFFFF",
    accentColor: "#CE1126",
    specialMove: "Aztec Spin",
    funnyTrait: "stadium-level passion",
  },
  {
    id: "usa",
    name: "USA",
    code: "USA",
    flag: "🇺🇸",
    category: "worldcup",
    primaryColor: "#3C3B6E",
    secondaryColor: "#B22234",
    accentColor: "#FFFFFF",
    specialMove: "Freedom Tackle",
    funnyTrait: "calling it soccer",
  },
  {
    id: "brazil",
    name: "Brazil",
    code: "BRA",
    flag: "🇧🇷",
    category: "worldcup",
    primaryColor: "#FFDF00",
    secondaryColor: "#009739",
    accentColor: "#002776",
    specialMove: "Samba Spin",
    funnyTrait: "permanent confidence",
  },
  {
    id: "argentina",
    name: "Argentina",
    code: "ARG",
    flag: "🇦🇷",
    category: "worldcup",
    primaryColor: "#75AADB",
    secondaryColor: "#FFFFFF",
    accentColor: "#F6B40E",
    specialMove: "Main Character Miracle",
    funnyTrait: "emotional storytelling",
  },
  {
    id: "uruguay",
    name: "Uruguay",
    code: "URU",
    flag: "🇺🇾",
    category: "worldcup",
    primaryColor: "#75AADB",
    secondaryColor: "#FFFFFF",
    accentColor: "#111827",
    specialMove: "Old-School Elbow",
    funnyTrait: "ancient tournament wisdom",
  },
  {
    id: "colombia",
    name: "Colombia",
    code: "COL",
    flag: "🇨🇴",
    category: "worldcup",
    primaryColor: "#FCD116",
    secondaryColor: "#003893",
    accentColor: "#CE1126",
    specialMove: "Cumbia Combo",
    funnyTrait: "dangerous rhythm",
  },
  {
    id: "ecuador",
    name: "Ecuador",
    code: "ECU",
    flag: "🇪🇨",
    category: "worldcup",
    primaryColor: "#FFD100",
    secondaryColor: "#034EA2",
    accentColor: "#ED1C24",
    specialMove: "Altitude Slam",
    funnyTrait: "thin-air confidence",
  },
  {
    id: "paraguay",
    name: "Paraguay",
    code: "PAR",
    flag: "🇵🇾",
    category: "worldcup",
    primaryColor: "#D52B1E",
    secondaryColor: "#FFFFFF",
    accentColor: "#0038A8",
    specialMove: "Defensive Wallop",
    funnyTrait: "stubborn survival energy",
  },

  // Europe
  {
    id: "france",
    name: "France",
    code: "FRA",
    flag: "🇫🇷",
    category: "worldcup",
    primaryColor: "#0055A4",
    secondaryColor: "#FFFFFF",
    accentColor: "#EF4135",
    specialMove: "Luxury Counterattack",
    funnyTrait: "effortless superiority",
  },
  {
    id: "spain",
    name: "Spain",
    code: "ESP",
    flag: "🇪🇸",
    category: "worldcup",
    primaryColor: "#AA151B",
    secondaryColor: "#F1BF00",
    accentColor: "#111827",
    specialMove: "Possession Loop",
    funnyTrait: "passing until everyone ages",
  },
  {
    id: "england",
    name: "England",
    code: "ENG",
    flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    category: "worldcup",
    primaryColor: "#FFFFFF",
    secondaryColor: "#CE1124",
    accentColor: "#111827",
    specialMove: "Penalty Anxiety",
    funnyTrait: "historical disappointment",
  },
  {
    id: "portugal",
    name: "Portugal",
    code: "POR",
    flag: "🇵🇹",
    category: "worldcup",
    primaryColor: "#006600",
    secondaryColor: "#FF0000",
    accentColor: "#FFD700",
    specialMove: "Drama Header",
    funnyTrait: "beautiful chaos",
  },
  {
    id: "germany",
    name: "Germany",
    code: "GER",
    flag: "🇩🇪",
    category: "worldcup",
    primaryColor: "#111827",
    secondaryColor: "#DD0000",
    accentColor: "#FFCE00",
    specialMove: "Efficiency Strike",
    funnyTrait: "spreadsheet football",
  },
  {
    id: "netherlands",
    name: "Netherlands",
    code: "NED",
    flag: "🇳🇱",
    category: "worldcup",
    primaryColor: "#FF7900",
    secondaryColor: "#FFFFFF",
    accentColor: "#21468B",
    specialMove: "Total Football Tornado",
    funnyTrait: "tactical overthinking",
  },
  {
    id: "belgium",
    name: "Belgium",
    code: "BEL",
    flag: "🇧🇪",
    category: "worldcup",
    primaryColor: "#000000",
    secondaryColor: "#FFD90C",
    accentColor: "#EF3340",
    specialMove: "Golden Generation Flashback",
    funnyTrait: "almost-there energy",
  },
  {
    id: "croatia",
    name: "Croatia",
    code: "CRO",
    flag: "🇭🇷",
    category: "worldcup",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    accentColor: "#171796",
    specialMove: "Extra-Time Curse",
    funnyTrait: "refusing to age",
  },
  {
    id: "switzerland",
    name: "Switzerland",
    code: "SUI",
    flag: "🇨🇭",
    category: "worldcup",
    primaryColor: "#D52B1E",
    secondaryColor: "#FFFFFF",
    accentColor: "#111827",
    specialMove: "Neutral Knockout",
    funnyTrait: "quietly dangerous",
  },
  {
    id: "austria",
    name: "Austria",
    code: "AUT",
    flag: "🇦🇹",
    category: "worldcup",
    primaryColor: "#ED2939",
    secondaryColor: "#FFFFFF",
    accentColor: "#111827",
    specialMove: "Alpine Press",
    funnyTrait: "mountain discipline",
  },
  {
    id: "denmark",
    name: "Denmark",
    code: "DEN",
    flag: "🇩🇰",
    category: "worldcup",
    primaryColor: "#C60C30",
    secondaryColor: "#FFFFFF",
    accentColor: "#111827",
    specialMove: "Nordic Shoulder Check",
    funnyTrait: "calm menace",
  },
  {
    id: "norway",
    name: "Norway",
    code: "NOR",
    flag: "🇳🇴",
    category: "worldcup",
    primaryColor: "#BA0C2F",
    secondaryColor: "#FFFFFF",
    accentColor: "#00205B",
    specialMove: "Viking Charge",
    funnyTrait: "ice-cold optimism",
  },
  {
    id: "scotland",
    name: "Scotland",
    code: "SCO",
    flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    category: "worldcup",
    primaryColor: "#005EB8",
    secondaryColor: "#FFFFFF",
    accentColor: "#111827",
    specialMove: "Bagpipe Bash",
    funnyTrait: "glorious suffering",
  },
  {
    id: "czechia",
    name: "Czechia",
    code: "CZE",
    flag: "🇨🇿",
    category: "worldcup",
    primaryColor: "#D7141A",
    secondaryColor: "#FFFFFF",
    accentColor: "#11457E",
    specialMove: "Bohemian Break",
    funnyTrait: "quiet tournament menace",
  },
  {
    id: "turkiye",
    name: "Türkiye",
    code: "TUR",
    flag: "🇹🇷",
    category: "worldcup",
    primaryColor: "#E30A17",
    secondaryColor: "#FFFFFF",
    accentColor: "#111827",
    specialMove: "Crescent Smash",
    funnyTrait: "maximum emotional volume",
  },
  {
    id: "sweden",
    name: "Sweden",
    code: "SWE",
    flag: "🇸🇪",
    category: "worldcup",
    primaryColor: "#006AA7",
    secondaryColor: "#FECC00",
    accentColor: "#FFFFFF",
    specialMove: "Nordic Flick",
    funnyTrait: "minimalist chaos",
  },
  {
    id: "bosnia",
    name: "Bosnia and Herzegovina",
    code: "BIH",
    flag: "🇧🇦",
    category: "worldcup",
    primaryColor: "#002395",
    secondaryColor: "#FECB00",
    accentColor: "#FFFFFF",
    specialMove: "Balkan Thunder",
    funnyTrait: "emotional long shots",
  },

  // Africa
  {
    id: "morocco",
    name: "Morocco",
    code: "MAR",
    flag: "🇲🇦",
    category: "worldcup",
    primaryColor: "#C1272D",
    secondaryColor: "#006233",
    accentColor: "#FFFFFF",
    specialMove: "Atlas Counter",
    funnyTrait: "giant-killer confidence",
  },
  {
    id: "senegal",
    name: "Senegal",
    code: "SEN",
    flag: "🇸🇳",
    category: "worldcup",
    primaryColor: "#00853F",
    secondaryColor: "#FDEF42",
    accentColor: "#E31B23",
    specialMove: "Lion Leap",
    funnyTrait: "fearless rhythm",
  },
  {
    id: "tunisia",
    name: "Tunisia",
    code: "TUN",
    flag: "🇹🇳",
    category: "worldcup",
    primaryColor: "#E70013",
    secondaryColor: "#FFFFFF",
    accentColor: "#111827",
    specialMove: "Carthage Clash",
    funnyTrait: "underdog stubbornness",
  },
  {
    id: "egypt",
    name: "Egypt",
    code: "EGY",
    flag: "🇪🇬",
    category: "worldcup",
    primaryColor: "#CE1126",
    secondaryColor: "#FFFFFF",
    accentColor: "#000000",
    specialMove: "Pharaoh Strike",
    funnyTrait: "ancient pressure",
  },
  {
    id: "algeria",
    name: "Algeria",
    code: "ALG",
    flag: "🇩🇿",
    category: "worldcup",
    primaryColor: "#006233",
    secondaryColor: "#FFFFFF",
    accentColor: "#D21034",
    specialMove: "Desert Burst",
    funnyTrait: "chaotic momentum",
  },
  {
    id: "ghana",
    name: "Ghana",
    code: "GHA",
    flag: "🇬🇭",
    category: "worldcup",
    primaryColor: "#CE1126",
    secondaryColor: "#FCD116",
    accentColor: "#006B3F",
    specialMove: "Black Star Blast",
    funnyTrait: "trauma-powered resilience",
  },
  {
    id: "cote-divoire",
    name: "Côte d'Ivoire",
    code: "CIV",
    flag: "🇨🇮",
    category: "worldcup",
    primaryColor: "#F77F00",
    secondaryColor: "#FFFFFF",
    accentColor: "#009E60",
    specialMove: "Elephant Charge",
    funnyTrait: "heavyweight energy",
  },
  {
    id: "south-africa",
    name: "South Africa",
    code: "RSA",
    flag: "🇿🇦",
    category: "worldcup",
    primaryColor: "#007A4D",
    secondaryColor: "#FFB612",
    accentColor: "#DE3831",
    specialMove: "Vuvuzela Shockwave",
    funnyTrait: "sound-based warfare",
  },
  {
    id: "dr-congo",
    name: "DR Congo",
    code: "COD",
    flag: "🇨🇩",
    category: "worldcup",
    primaryColor: "#007FFF",
    secondaryColor: "#F7D618",
    accentColor: "#CE1021",
    specialMove: "Leopard Lunge",
    funnyTrait: "wild-card force",
  },
  {
    id: "cabo-verde",
    name: "Cabo Verde",
    code: "CPV",
    flag: "🇨🇻",
    category: "worldcup",
    primaryColor: "#003893",
    secondaryColor: "#FFFFFF",
    accentColor: "#CF2027",
    specialMove: "Island Ambush",
    funnyTrait: "small-team audacity",
  },

  // Asia / Oceania
  {
    id: "japan",
    name: "Japan",
    code: "JPN",
    flag: "🇯🇵",
    category: "worldcup",
    primaryColor: "#FFFFFF",
    secondaryColor: "#BC002D",
    accentColor: "#111827",
    specialMove: "Anime Comeback Arc",
    funnyTrait: "boss-level discipline",
  },
  {
    id: "south-korea",
    name: "South Korea",
    code: "KOR",
    flag: "🇰🇷",
    category: "worldcup",
    primaryColor: "#FFFFFF",
    secondaryColor: "#CD2E3A",
    accentColor: "#0047A0",
    specialMove: "Late Drama Sprint",
    funnyTrait: "90th-minute belief",
  },
  {
    id: "iran",
    name: "Iran",
    code: "IRN",
    flag: "🇮🇷",
    category: "worldcup",
    primaryColor: "#239F40",
    secondaryColor: "#FFFFFF",
    accentColor: "#DA0000",
    specialMove: "Persian Wall",
    funnyTrait: "defensive patience",
  },
  {
    id: "saudi-arabia",
    name: "Saudi Arabia",
    code: "KSA",
    flag: "🇸🇦",
    category: "worldcup",
    primaryColor: "#006C35",
    secondaryColor: "#FFFFFF",
    accentColor: "#111827",
    specialMove: "Desert Upset",
    funnyTrait: "one famous result away from chaos",
  },
  {
    id: "australia",
    name: "Australia",
    code: "AUS",
    flag: "🇦🇺",
    category: "worldcup",
    primaryColor: "#0B6B3A",
    secondaryColor: "#FFD200",
    accentColor: "#FFFFFF",
    specialMove: "Kangaroo Kick",
    funnyTrait: "unrealistic optimism",
  },
  {
    id: "qatar",
    name: "Qatar",
    code: "QAT",
    flag: "🇶🇦",
    category: "worldcup",
    primaryColor: "#8A1538",
    secondaryColor: "#FFFFFF",
    accentColor: "#111827",
    specialMove: "Desert Mirage",
    funnyTrait: "air-conditioned confidence",
  },
  {
    id: "uzbekistan",
    name: "Uzbekistan",
    code: "UZB",
    flag: "🇺🇿",
    category: "worldcup",
    primaryColor: "#1EB6E7",
    secondaryColor: "#FFFFFF",
    accentColor: "#009A44",
    specialMove: "Silk Road Strike",
    funnyTrait: "newcomer chaos",
  },
  {
    id: "iraq",
    name: "Iraq",
    code: "IRQ",
    flag: "🇮🇶",
    category: "worldcup",
    primaryColor: "#CE1126",
    secondaryColor: "#FFFFFF",
    accentColor: "#000000",
    specialMove: "Mesopotamia Smash",
    funnyTrait: "ancient comeback energy",
  },
  {
    id: "jordan",
    name: "Jordan",
    code: "JOR",
    flag: "🇯🇴",
    category: "worldcup",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    accentColor: "#CE1126",
    specialMove: "Red Triangle Rush",
    funnyTrait: "unexpected tournament spice",
  },
  {
    id: "new-zealand",
    name: "New Zealand",
    code: "NZL",
    flag: "🇳🇿",
    category: "worldcup",
    primaryColor: "#111827",
    secondaryColor: "#FFFFFF",
    accentColor: "#C8102E",
    specialMove: "Kiwi Counter",
    funnyTrait: "quiet island confidence",
  },

  // CONCACAF additional
  {
    id: "haiti",
    name: "Haiti",
    code: "HAI",
    flag: "🇭🇹",
    category: "worldcup",
    primaryColor: "#00209F",
    secondaryColor: "#D21034",
    accentColor: "#FFFFFF",
    specialMove: "Caribbean Spark",
    funnyTrait: "pure underdog energy",
  },
  {
    id: "curacao",
    name: "Curaçao",
    code: "CUW",
    flag: "🇨🇼",
    category: "worldcup",
    primaryColor: "#002B7F",
    secondaryColor: "#F9E814",
    accentColor: "#FFFFFF",
    specialMove: "Island Curveball",
    funnyTrait: "tiny-team swagger",
  },
  {
    id: "panama",
    name: "Panama",
    code: "PAN",
    flag: "🇵🇦",
    category: "worldcup",
    primaryColor: "#005293",
    secondaryColor: "#FFFFFF",
    accentColor: "#D21034",
    specialMove: "Canal Cut",
    funnyTrait: "narrow-path survival",
  },

  // Chaos Teams
  {
    id: "china",
    name: "China",
    code: "CHN",
    flag: "🇨🇳",
    category: "chaos",
    primaryColor: "#DE2910",
    secondaryColor: "#FFDE00",
    accentColor: "#FFFFFF",
    specialMove: "Infinite Hope",
    funnyTrait: "mathematical qualification scenarios",
  },
  {
    id: "var-united",
    name: "VAR United",
    code: "VAR",
    flag: "📺",
    category: "chaos",
    primaryColor: "#111827",
    secondaryColor: "#22C55E",
    accentColor: "#FFFFFF",
    specialMove: "Five-Minute Review",
    funnyTrait: "ruining celebrations",
  },
  {
    id: "ai-fc",
    name: "AI FC",
    code: "AIFC",
    flag: "🤖",
    category: "chaos",
    primaryColor: "#6D28D9",
    secondaryColor: "#22D3EE",
    accentColor: "#FFFFFF",
    specialMove: "Hallucinated Tactics",
    funnyTrait: "confidently wrong analysis",
  },
  {
    id: "kangaroo-federation",
    name: "Kangaroo Federation",
    code: "ROO",
    flag: "🦘",
    category: "chaos",
    primaryColor: "#0B6B3A",
    secondaryColor: "#FFD200",
    accentColor: "#FFFFFF",
    specialMove: "Double Kangaroo Kick",
    funnyTrait: "illegal jumping advantage",
  },
  {
    id: "software-engineers",
    name: "Software Engineers",
    code: "DEV",
    flag: "👨‍💻",
    category: "chaos",
    primaryColor: "#0F172A",
    secondaryColor: "#38BDF8",
    accentColor: "#A3E635",
    specialMove: "Production Incident",
    funnyTrait: "deploying directly to midfield",
  },
  {
    id: "coffee-addicts",
    name: "Coffee Addicts",
    code: "CAF",
    flag: "☕",
    category: "chaos",
    primaryColor: "#78350F",
    secondaryColor: "#FDE68A",
    accentColor: "#FFFFFF",
    specialMove: "Caffeine Rush",
    funnyTrait: "unstable but energetic",
  },
];

// Sorted alphabetically by name for the dropdown listing (the master `teams`
// array keeps its original order for random/default selection).
const byName = (a: Team, b: Team) => a.name.localeCompare(b.name);

export const worldCupTeams = teams
  .filter((t) => t.category === "worldcup")
  .sort(byName);
export const chaosTeams = teams.filter((t) => t.category === "chaos").sort(byName);

export function getTeamById(id: string): Team | undefined {
  return teams.find((t) => t.id === id);
}
